# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-02 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20160227_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='veggiesailorentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veggiesailorentry',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
