env:
  global:
    - secure: DdWdwt9ImwDWruQmlBHG1+GqhC9a5VRgSGVma1uSvR6s1KggrYR23M6O3ihSO76KNQBdXpEb0l2y38oODT3lkqCH6Znj1G4OPDFL3CCSnoseUWlPL4IGGSsIClvffTMK4GyMHTtHFk4XUO3ACagHDBZOMUxXuvqXQMCc8sTtjlY=
    - secure: jXfXoDkm1X4yFAAm5A51LUyaDyWMTGKPPCDVA/3qzwoBQnk3uE8NOha3hxV5Sunyr8ZZJeY0jiQe7fLgwOUqGZddyfZ94zdofDE2CcdJsXtC48mthhbzFS68uPxYbf/CAF6c6pH029lo/09jGeuukyF+VvRHD+N2vnDZTt+71d0=
language: python
python:
  - "3.3"
  - "3.4"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database vegbasket;' -U postgres        
before_install:
  - pip install codecov
# command to install dependencies
install: "ls;pip install -r requirements.txt;cp vegbasketapp/vegbasketapp/settings_secret.py.example vegbasketapp/vegbasketapp/settings_secret.py; pip install coveralls"
# command to run tests
script: "cd vegbasketapp;coverage run --source='.' manage.py test --settings vegbasketapp.settings_travis"
after_success:
  - coveralls
  - codecov
addons:
  sauce_connect: true
