language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database vegbasket;' -U postgres        
# command to install dependencies
install: "ls;pip install -r requirements.txt"
# command to run tests
script: "python vegbasketapp/manage.py test --settings vegbasketapp.settings_travis"
