# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_visit_visit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
