# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ['-ingredient']},
        ),
    ]
