from django.utils.translation import ugettext_lazy as _

results = ['Eclectic (Fusion)',
 'Eclectic (Varied)',
 'Mediterranean',
 'Spanish',
 'Italian',
 'Middle Eastern/Persian',
 'English',
 'Jewish (Eastern European)',
 'Russian',
 'Raw Food',
 'French',
 'Chinese',
 'Brazilian',
 'German',
 'Korean',
 'Greek',
 'American',
 'Indian',
 'Macrobiotic',
 'Hungarian',
 'Pizza',
 'Indian (Southern)',
 'Vietnamese',
 'South American',
 'Japanese',
 'Thai',
 'Cantonese',
 'Dim Sum',
 'Taiwanese',
 'Szechuan',
 'Indian (Northern)',
 'Italian (Southern)',
 'Deli',
 'Mexican',
 'Indonesian',
 'Caribbean',
 'Sri Lankan',
 'African',
 'Soul Food',
 'Tibetan',
 'Turkish',
 'Ethiopian/Eritrean',
 'Nepalese',
 'Italian (Northern)',
 'Cambodian',
 'Central American',
 'Indo-Chinese',
 'Lebanese',
 'Moroccan',
 'Romanian',
 'Tex-Mex',
 'Hmong',
 'Malaysian',
 'Jewish (Sephardic)',
 'Cajun',
 'Mongolian',
 'Egyptian',
 'Hunanese',
 'South African',
 'Ghanaian',
 'North African',
 'West African',
 'Burmese',
 'Northern (Beijing)',
 'Hot Pot',
 'Afghani',
 'Laotian',
 'Filipino',
 'Hakka',
 'Kurdish']

output = _(' '.join(results))